import React, { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Code from "../components/Code/Code";
import Happy from "../components/Happy/Happy";

export default function Home() {
  const [isHappy, setIsHappy] = useState(true);

  const imageClick = () => {
    setIsHappy(!isHappy);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Happy Birthday Lucie !</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=League+Spartan:wght@700&display=swap"
          rel="stylesheet"
        ></link>
        <script type="text/javascript">party.confetti(document.body) ;</script>
      </Head>

      <div className={styles.header}>
        <button className={styles.button} onClick={imageClick}>Clique moi pour voir</button>
      </div>

      {!isHappy && <Code />}

      {isHappy && <Happy />}

    </div>
  );
}
